---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	retrieve(retrieve)
	question(question)
	wait(wait)
	assess(assess)
	report(report)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	assess --> supervisor;
	question --> wait;
	retrieve --> question;
	supervisor -.-> report;
	supervisor -.-> retrieve;
	wait -.-> assess;
	wait -.-> report;
	report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
